[package]
name = "ink-sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
polkavm = { git = "https://github.com/paritytech/polkavm"}
anyhow = "1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"

