name: Build ink-sandbox binaries

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            ext: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release binary
        working-directory: ./ink-sandbox
        run: cargo build --release --target ${{ matrix.target }}

      - name: Move binary to /bin/ink-sandbox/
        run: |
          mkdir -p bin/ink-sandbox
          cp ink-sandbox/target/${{ matrix.target }}/release/ink-sandbox${{ matrix.ext }} bin/ink-sandbox/ink-sandbox-${{ matrix.target }}${{ matrix.ext }}

      - uses: actions/upload-artifact@v4
        with:
          name: ink-sandbox-${{ matrix.target }}
          path: bin/ink-sandbox/
