name: Build ink-sandbox binaries

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Build ink-sandbox
        working-directory: ./ink-sandbox
        run: cargo build --release --target ${{ matrix.target }}

      - name: Copy to bin/ink-sandbox
        shell: bash
        run: |
          mkdir -p bin/ink-sandbox
          cp ink-sandbox/target/${{ matrix.target }}/release/ink-sandbox${{ matrix.ext }} bin/ink-sandbox/ink-sandbox-${{ matrix.target }}${{ matrix.ext }}

      - name: Commit and push bin/
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bin/
          git commit -m "Update binaries for ${{ matrix.target }}" || echo "No changes"
          git push
