name: Build ink-sandbox binaries

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            ext: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
          targets: ${{ matrix.target }}

      - name: Build ink-sandbox
        working-directory: ./ink-sandbox
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare bin folder
        run: |
          mkdir -p bin/ink-sandbox
          cp ink-sandbox/target/${{ matrix.target }}/release/ink-sandbox${{ matrix.ext }} bin/ink-sandbox/ink-sandbox-${{ matrix.target }}${{ matrix.ext }}

      - name: Commit and push binaries
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bin/
          git commit -m "Update binaries for ${{ matrix.target }}" || echo "No changes"
          git push
